version: 2
jobs:
  build:
    docker:
      - image: rabits/qt:5.10-desktop
    steps:
      - checkout
      - run:
          name: Qmake
          command: qmake
      - run:
          name: Build
          command: make
