version: 2
jobs:
  build:
    docker:
      - image: docker pull rabits/qt:5.10-desktop
    steps:
      - checkout
      - run:
          name: Build
          command: qmake
	  command: make clean
          command: make
