version: 2
jobs:
  build:
    docker:
      - image: rabits/qt:5.10-desktop
    checkout:
      post:
        - git submodule sync
        - git submodule update --init
    steps:
      - run:
          name: Qmake
          command: qmake
      - run:
          name: Build
          command: make
