version: 2.1

commands:
  build:
    steps:
      - checkout
      - run:
          name: Qmake
          command: qmake
      - run:
          name: Build
          command: make -j 36

executors:
  docker-executor:
    docker:
      - image: heliconwave/circleci-ubuntu-18.04:latest

jobs:
  build-via-docker:
    executor: docker-executor
    steps:
      - build

workflows:
  build-via-docker:
    jobs:
      - build-via-docker

# jobs:
#   build:
#     docker:
#       - image: heliconwave/qt5:latest
#     steps:
#       - checkout
#       - run:
#           name: Qmake
#           command: qmake
#       - run:
#           name: Build
#           command: make -j 36
