version: 2
jobs:
  build:
    docker:
      - image: circleci/build-image:ubuntu-14.04-XXL-1327-3401d20
    steps:
      - checkout
      - run:
          name: Build
          command: qmake
          command: make